name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        run: |
          rustup target add wasm32-unknown-unknown
          rustup toolchain install stable
          rustup default stable
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Install wasm-bindgen
        run: cargo install --force wasm-bindgen-cli
      - name: Build Book
        run: |
          mdbook build bevy-workshop
      - name: Build wasm game
        run: |
          cargo build --target wasm32-unknown-unknown --release
          wasm-bindgen --out-dir bevy-workshop/book --out-name workshop --target web target/wasm32-unknown-unknown/release/bevy_workshop-rustweek-2025.wasm
      - name: Optimize Wasm
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: bevy-workshop/book/workshop-rustweek-2025_bg.wasm
      - name: Copy assets
        run: cp -r assets bevy-workshop/book/
      - name: Copy restart-audio-context.js for wasm
        run: cp wasm/restart-audio-context.js bevy-workshop/book/
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "bevy-workshop/book"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
